### ISSUE TITLE
Atualizar a URL de prod conforme novo domínio

### ISSUE THREAD

**Issue by bellatriz** [PauloGoncalvesBH/sample-supertest#2]
Ao rodar os testes ele não consegue encontrar o servidor e retorna erros, observei que o domínio no arquivo _producao.config.js_ ainda está como: https://www.serverest.dev/, sendo que atualmente é apenas https://serverest.dev/.

**Comment by PauloGoncalvesBH** [comment]
Oi @bellatriz, fiz a correção, muito obrigado pela issue sugerindo a correção :D 

Atualize o seu código local com `git pull` para poder utilizar a configuração correta.
